# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43f4dafdd06fbd5c3491b2839dd1d5733256ccd8bb2a79fed4b9e9c0a7af4bffa826d0f3fc5ab4964e80121c82af60c21b8ca056076fed34a9998bf97b92eec7

test:
  secret_key_base: f59c5c4e9cf59d1226df45296b63219ba0c2d41868a1669b313b15ff01819b9a817ee5fb03ad99c1c6497c6f497d82c2fdbee9d4e747628edb5c7c19fbee950b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>